version: '3.9'

services:
  django:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - rabbitmq

  celery:
    build: .
    container_name: celery_worker
    command: celery -A base worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - django
      - rabbitmq

  beat:
    build: .
    container_name: celery_beat
    command: celery -A base beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - django
      - rabbitmq

  flower:
    image: mher/flower
    container_name: flower
    command: flower --broker=amqp://guest:guest@rabbitmq:5672//
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
